const uuid = require('uuid');
const friends = require('./users');
const products = require('./products');
const wishList = products.filter(item => item.tag === 'CANDY');
const wish= wishList[0];

const greenPost = {
  _id: uuid(),
  author:   {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'homer',
    lastName: 'simpson',
    perfilImg: require('../../assets/images/persons/homer.jpg'),
  },
  date: Date.now(),
  img: require(`../../assets/images/random/springfield.png`),
  title: 'lorem ipsum',
  subTitle: 'lorem ipsum subtitle',
  history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
  likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
  gifts: Math.floor(Math.random() * 9) + 1,
  wish: Math.floor(Math.random() * 9) + 1,  
}

const posts = [
  {
    _id: uuid(),
    author:   {
      _id: uuid(),
      url: `/perfil/${uuid()}`,
      name: 'homer',
      lastName: 'simpson',
      perfilImg: require('../../assets/images/persons/homer.jpg'),
    },
    date: Date.now(),
    img: require(`../../assets/images/random/r1.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author:   {
      _id: uuid(),
      url: `/perfil/${uuid()}`,
      name: 'homer',
      lastName: 'simpson',
      perfilImg: require('../../assets/images/persons/homer.jpg'),
    },
    date: Date.now(),
    img: require(`../../assets/images/random/r2.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author:   {
      _id: uuid(),
      url: `/perfil/${uuid()}`,
      name: 'homer',
      lastName: 'simpson',
      perfilImg: require('../../assets/images/persons/homer.jpg'),
    },
    date: Date.now(),
    img: require(`../../assets/images/random/r3.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author:   {
      _id: uuid(),
      url: `/perfil/${uuid()}`,
      name: 'homer',
      lastName: 'simpson',
      perfilImg: require('../../assets/images/persons/homer.jpg'),
    },
    date: Date.now(),
    img: require(`../../assets/images/random/r4.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author:   {
      _id: uuid(),
      url: `/perfil/${uuid()}`,
      name: 'homer',
      lastName: 'simpson',
      perfilImg: require('../../assets/images/persons/homer.jpg'),
    },
    date: Date.now(),
    img: require(`../../assets/images/random/r5.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },        
]


const admin = {
  _id: uuid(),
  owner: true,
  firstTime: false,
  mail: 'admin@mail.com',
  pass: '123456',
  name: "homer",
  lastName: "simpson",
  birthday: '12/05/1956',
  sex: 'male',
  posts,
  greenPost,
  perfilImg: require('../../assets/images/persons/homer.jpg'),
  originalCity: 'springfield',
  actualCity: 'springField',
  primarySchool: 'escuela primaria de springfield',
  secondarySchool: 'preparatoria de springfield',
  university: 'tecnologico de springfield',
  job: 'uno de los esclavos del sector 7G',
  history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  wish,
  wallet: 50,
  friends,
}

module.exports = admin;
