const uuid = require('uuid/v1');

const authors = [
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'sam',
    lastName: 'ganya',
    perfilImg: require('../../assets/images/persons/person-0.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'jhon',
    lastName: 'doe',
    perfilImg: require('../../assets/images/persons/person-1.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'tara',
    lastName: 'earth',
    perfilImg: require('../../assets/images/persons/person-2.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'anne',
    lastName: 'fire',
    perfilImg: require('../../assets/images/persons/person-3.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'lisa',
    lastName: 'water',
    perfilImg: require('../../assets/images/persons/person-4.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'star',
    lastName: 'green',
    perfilImg: require('../../assets/images/persons/person-5.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'bella',
    lastName: 'donna',
    perfilImg: require('../../assets/images/persons/person-6.jpg'),
  },
  {
    _id: uuid(),
    url: `/perfil/${uuid()}`,
    name: 'rachel',
    lastName: 'wind',
    perfilImg: require('../../assets/images/persons/person-7.jpg'),
  },
]

const posts = [
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r1.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r2.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r3.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r4.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r5.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r6.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
  {
    _id: uuid(),
    author: authors[Math.floor(Math.random() * 7) +1],
    date: Date.now(),
    img: require(`../../assets/images/random/r7.jpg`),
    title: 'lorem ipsum',
    subTitle: 'lorem ipsum subtitle',
    history: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
    comments: Array(Math.floor(Math.random() * 9) + 1).fill('hola mundo'),
    likes: Array(Math.floor(Math.random() * 9) + 1).fill(0),
    gifts: Math.floor(Math.random() * 9) + 1,
    wish: Math.floor(Math.random() * 9) + 1,
  },
]

module.exports = posts;
