export const ON_LAYOUT_CAMERAPICKER = 'ON_LAYOUT_CAMERAPICKER';
export const ON_CURRENT_USER = 'ON_CURRENT_USER';
export const ON_CURRENT_USER_POST = 'ON_CURRENT_USER_POST';
export const ON_MACHINE_PERFIL = 'ON_MACHINE_PERFIL';
export const ON_MACHINE_PRODUCT = 'ON_MACHINE_PRODUCT';
export const ON_STORE_SECTION = 'ON_STORE_SECTION';
export const ON_STORE_PRODUCT = 'ON_STORE_PRODUCT';



export const storeSection = {
  PROMOTION: 'PROMOTION',
  JEWEL: 'JEWEL',
  EBOOK: 'EBOOK',
  CANDY: 'CANDY',
  MUSIC: 'MUSIC',
  TV: 'TV',
  TOY: 'TOY',
}